package com.localkart.customer

import android.Manifest
import android.os.Build
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.runtime.*
import androidx.compose.ui.platform.LocalContext
import com.localkart.common.auth.AuthManager
import com.localkart.common.model.UserRole
import com.localkart.common.ui.theme.LocalKartTheme
import com.localkart.customer.nav.CustomerRoot
import com.localkart.customer.ui.common.AuthScreen
import kotlinx.coroutines.launch

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            LocalKartTheme {
                val context = LocalContext.current
                val scope = rememberCoroutineScope()
                var loggedIn by remember { mutableStateOf(AuthManager.isLoggedIn) }

                // React to sign-in/sign-out anywhere in the app (e.g. Logout button).
                DisposableEffect(Unit) {
                    val stop = AuthManager.addAuthListener { loggedIn = it }
                    onDispose { stop() }
                }

                // Notification permission (Android 13+) + register FCM token after login.
                val notifPerm = rememberLauncherForActivityResult(
                    ActivityResultContracts.RequestPermission()
                ) { }
                LaunchedEffect(loggedIn) {
                    if (loggedIn) {
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                            notifPerm.launch(Manifest.permission.POST_NOTIFICATIONS)
                        }
                        com.localkart.common.notify.PushTokens.register()
                    }
                }

                // Web client id is generated by the google-services plugin once Google
                // sign-in is enabled. Resolve by name so the build never breaks if absent.
                val webClientId = remember {
                    val id = context.resources.getIdentifier(
                        "default_web_client_id", "string", context.packageName
                    )
                    if (id != 0) context.getString(id) else ""
                }

                val launcher = rememberLauncherForActivityResult(
                    ActivityResultContracts.StartActivityForResult()
                ) { result ->
                    scope.launch {
                        val res = AuthManager.handleResult(result.data, UserRole.CUSTOMER)
                        if (res.isSuccess) {
                            loggedIn = true
                        } else {
                            Toast.makeText(
                                context,
                                "Sign-in failed: ${res.exceptionOrNull()?.message}",
                                Toast.LENGTH_LONG
                            ).show()
                        }
                    }
                }

                if (loggedIn) {
                    CustomerRoot()
                } else {
                    AuthScreen(
                        onGoogleSignIn = {
                            if (webClientId.isEmpty()) {
                                Toast.makeText(
                                    context,
                                    "Enable Google sign-in in Firebase, then re-download google-services.json",
                                    Toast.LENGTH_LONG
                                ).show()
                            } else {
                                launcher.launch(AuthManager.googleSignInIntent(context, webClientId))
                            }
                        },
                        onPhoneSignIn = {
                            Toast.makeText(context, "Phone OTP coming soon", Toast.LENGTH_SHORT).show()
                        }
                    )
                }
            }
        }
    }
}
